// Auto-generated from SNAPPO_Service_Catalog.xlsx
// 10 main categories with 232 services

export const CATEGORIES = {
  'Education & Learning': [
    'Mathematics (Classes 1-5)',
    'Mathematics (Classes 6-8)',
    'Mathematics (Classes 9-10)',
    'Science (Classes 6-8)',
    'Science (Classes 9-10)',
    'English & Languages',
    'JEE Coaching (Individual)',
    'NEET Coaching',
    'CAT/MBA Entrance',
    'UPSC/Civil Services',
    'Spoken English (Beginner)',
    'IELTS Preparation',
    'Grammar & Writing',
    'Hindi Learning',
    'Kannada/Tamil/Telugu',
    'French (Beginner)',
    'German (Beginner)',
    'MS Office Training',
    'Python Programming',
    'Web Development',
    'Photoshop Basics',
    'Canva Training',
    'Video Editing',
    'Resume Writing',
    'Mock Interviews',
    'LinkedIn Optimization',
    'Chess Coaching',
    'Creative Writing',
    'Coding for Kids',
  ],
  'Food & Culinary': [
    'Vegetarian Lunch Tiffin',
    'Non-Vegetarian Lunch',
    'Jain Food Tiffin',
    'Keto/Low-Carb Meals',
    'Vegetarian Dinner',
    'Non-Vegetarian Dinner',
    'Lunch Only (Mon-Sat)',
    'Lunch + Dinner Package',
    'South Indian Breakfast',
    'Paratha Breakfast',
    'Diabetic-Friendly Meals',
    'Vegan Meals',
    'High-Protein Meals',
    'Birthday Cake (Custom)',
    'Kids Party Catering',
    'Adult Party Snacks',
    'Diwali Sweets Box',
    'Ganesh Chaturthi Modak',
    'Eid Biryani & Sewai',
    'Cupcakes (Dozen)',
    'Cookies (Dozen)',
    'Brownies',
    'Basic Cooking for Bachelors',
    'Regional Cuisine Classes',
    'Baking Classes',
    'Nutrition Consultation',
    'Meal Planning Service',
  ],
  'Sports & Fitness': [
    'Batting Technique',
    'Bowling Technique',
    'All-Round Cricket',
    'Football Skills Training',
    'Shooting & Finishing',
    'Beginner Badminton',
    'Advanced Badminton',
    'Learn to Swim (Beginner)',
    'Kids Swimming (5-12)',
    'Home Personal Training',
    'Weight Loss Program',
    'Muscle Building',
    'Park Group Training',
    'Zumba Classes',
    'Hatha Yoga (Beginner)',
    'Power Yoga',
    'Prenatal Yoga',
    'Guided Meditation',
    'Pranayama Basics',
    'Karate (Kids)',
    'Kickboxing',
    'Women\'s Self-Defense',
    'Basic Self-Defense',
  ],
  'Spiritual & Wellness': [
    'Daily Home Pooja',
    'Satyanarayan Pooja',
    'Naming Ceremony',
    'Thread Ceremony',
    'Housewarming Pooja',
    'Wedding Ceremony',
    'Diwali Lakshmi Pooja',
    'Ganesh Chaturthi Pooja',
    'Nikah Ceremony',
    'Quran Recitation',
    'House Blessing (Christian)',
    'Kundli Making',
    'Horoscope Reading',
    'Marriage Matching',
    'Career Consultation',
    'Tarot Card Reading',
    'Numerology',
    'Palmistry',
    'Home Vastu Consultation',
    'Office Vastu',
    'Hatha Yoga',
    'Guided Meditation',
    'Pranayama',
  ],
  'Arts & Music': [
    'Hindustani Classical (Beginner)',
    'Carnatic Singing',
    'Bollywood Singing',
    'Kids Singing Classes',
    'Acoustic Guitar (Beginner)',
    'Electric Guitar',
    'Keyboard (Beginner)',
    'Piano (Classical)',
    'Tabla (Beginner)',
    'Harmonium',
    'Flute/Bansuri',
    'Drum Kit (Beginner)',
    'Bharatanatyam',
    'Kathak',
    'Bollywood Dance (Beginner)',
    'Wedding Choreography',
    'Hip-Hop',
    'Salsa',
    'Drawing & Sketching',
    'Watercolor Painting',
    'Kids Art Classes',
    'Digital Drawing (Procreate)',
    'Calligraphy',
  ],
  'Technology Support': [
    'Android Phone Setup',
    'iPhone Setup',
    'App Installation',
    'Phone Backup Setup',
    'Laptop Setup',
    'Windows Installation',
    'MS Office Installation',
    'WiFi Router Setup',
    'Printer Setup',
    'Smart TV Setup',
    'Alexa/Google Home Setup',
    'WiFi Camera Installation',
    'WhatsApp Training',
    'UPI Payment Training',
    'Video Calling Setup',
    'Email Basics',
    'Phone Slow/Hanging Fix',
    'Virus Removal',
    'Computer Slow Fix',
    'Password Recovery',
    'Data Backup',
    'Cloud Storage Setup',
    'Simple Website Creation',
    'LinkedIn Profile Optimization',
  ],
  'Pet Care': [
    'Dog Sitting (Home Visit)',
    'Overnight Dog Boarding',
    'Vacation Pet Care',
    'Cat Sitting (Home Visit)',
    'Morning Dog Walk (30 min)',
    'Evening Dog Walk (30 min)',
    'Long Walk/Run (60 min)',
    'Dog Bath at Home',
    'Cat Bath',
    'Nail Trimming (Dogs)',
    'Professional Haircut',
    'Puppy Training',
    'Basic Obedience',
    'Behavioral Training',
    'Vet Transport',
    'Medication Administration',
    'Pet Photography',
    'Adoption Counseling',
    'Stray Feeding Program',
  ],
  'Event Management': [
    'Kids Birthday (20-30)',
    'Theme Party Planning',
    'Adult Birthday (20-50)',
    'Surprise Party',
    'Wedding Anniversary',
    'Romantic Anniversary Setup',
    'Baby Shower',
    'Gender Reveal',
    'Naming Ceremony Event',
    'Caterer Sourcing',
    'Decorator Coordination',
    'Entertainment Booking',
    'Photographer Booking',
    'Mehendi Function',
    'Sangeet Planning',
    'Small Home Wedding',
    'Event Day Coordination',
    'Vendor Management',
    'Invitation Design',
    'Event Theme Design',
  ],
  'Handymen Services': [
    'IKEA Furniture Assembly',
    'Study Table Assembly',
    'Bookshelf Assembly',
    'Bed Assembly',
    'TV Wall Mounting',
    'Shelf Installation',
    'Curtain Rod Installation',
    'Photo/Mirror Hanging',
    'Ceiling Fan Installation',
    'Water Purifier Install',
    'Light Bulb Replacement',
    'Switch Replacement',
    'Doorbell Installation',
    'Leaky Tap Fixing',
    'Toilet Flush Repair',
    'Shower Head Replacement',
    'Door Lock Adjustment',
    'Hinge Oiling',
    'Smart Doorbell Install',
    'WiFi Camera Mounting',
    'Wardrobe Organization',
    'Cable Management',
    'Wall Drilling',
  ],
  'Home & Personal Care': [
    'House Cleaning (1BHK)',
    'House Cleaning (2BHK)',
    'Post-Party Cleaning',
    'Kitchen Deep Cleaning',
    'Bathroom Deep Cleaning',
    'Sofa Cleaning',
    'Laundry Pickup & Delivery',
    'Ironing Only',
    'Women\'s Haircut',
    'Men\'s Haircut',
    'Kids Haircut',
    'Basic Facial',
    'Cleanup',
    'Waxing',
    'Threading',
    'Manicure & Pedicure',
    'Party Makeup',
    'Bridal Makeup',
    'Grocery Shopping',
    'Medicine Pickup',
    'Bill Payments (Offline)',
  ],
};

export const CATEGORY_LIST = Object.keys(CATEGORIES);

export const getCategoryIcon = (category) => {
  const icons = {
    'Education & Learning': '📚',
    'Food & Culinary': '🍳',
    'Sports & Fitness': '⚽',
    'Spiritual & Wellness': '🧘',
    'Arts & Music': '🎨',
    'Technology Support': '💻',
    'Pet Care': '🐾',
    'Event Management': '🎉',
    'Handymen Services': '🔧',
    'Home & Personal Care': '🏠'
  };
  return icons[category] || '📦';
};
